### ISSUE TITLE
Possibility to exclude files

### ISSUE THREAD

**Issue by diasjorge** [maorfr/skbn#7]
Hi, 

Would if be possible to exclude certain paths/folders from being copied?

Is this feature desirable for your project? If I were to implement such a feature to send a PR, do you have any tips to where it would be best implemented in your code base?

Thanks

**Comment by daxgames** [comment]
@diasjorge did you ever write this.  I need it too.

**Comment by diasjorge** [comment]
I'm not using this tool anymore. I'm using velero for kubernetes backups.
